[build]
  functions = "functions"
  publish = "public"

[functions]
  included_files = ["scripts/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200